### ISSUE TITLE
AttributeError using python3

### ISSUE THREAD

**Issue by morrolinux** [warchildmd/google-assistant-hotword-raspi#15]
Hello, when i use 
> python gassistant.py models/ok_google.pmdl
I get:
AttributeError: module 'google.assistant.embedded.v1alpha1.embedded_assistant_pb2' has no attribute 'EmbeddedAssistantStub'
PS: i had to install libpython3.4

**Comment by ghost** [comment]
Just on a side note, how did you install libpython3.4. im stuck there.

**Update**
sudo apt-get install libpython3.4

Ok after installing libpython3.4 I am also stuck here.

(env) pi@raspberrypi:~/google-assistant-hotword-raspi $ python gassistant.py models/ok_google.pmdl 
Traceback (most recent call last):
  File "gassistant.py", line 33, in <module>
    assistant = Assistant()
  File "/home/pi/google-assistant-hotword-raspi/assistant.py", line 84, in __init__
    self.assistant = embedded_assistant_pb2.EmbeddedAssistantStub(self.grpc_channel)
AttributeError: module 'google.assistant.embedded.v1alpha1.embedded_assistant_pb2' has no attribute 'EmbeddedAssistantStub'

**Comment by maheshyadav007** [comment]
is the above problem solved?

problem solved myself
thanks

**Comment by royka1** [comment]
How did you solve the problem? i'm struggling for day with it

**Comment by maheshyadav007** [comment]
Its not a big issue. EmbeddedAssistantStub is not in google.assistant.embedded.v1alpha1.embedded_assistant_pb2 instead it is in google.assistant.embedded.v1alpha1.embedded_assistant_pb2_grpc so change the module name in assistant.py(You need to change it in 2 places(line 84 and 190)).
After this most probably you would get one more error something like assistant helper.... For this you need to change the line 136 and 144 by replacing the function name from assistant_helpers.py which is in googlesamples.assistant.grpc . After doing these changes you should be good to go.

Hope this helps!!

**Comment by maheshyadav007** [comment]
Replied to your Problem. Have a look.

**Comment by royka1** [comment]
Thank you very much for the reply. I've tried these changes, but when i look in the assistant_helpers.py i've got less then 136 lines. It also has at the top at import the line "google.assistant.embedded.v1alpha**2**.embedded_assistant_pb2". When i don't change that file, it comes a bit further then before. I identifies the hotword but after that i see a lot of errors in a loop. Also tried to change that line to v1alpha1 and, but that didn't work of course. 

Edit: Downloaded an older assistent_helper.py, this file i didn't have to edit. Thank you very much for your help

**Comment by maheshyadav007** [comment]
Can you show me the error

**Comment by maheshyadav007** [comment]
If possible attach a ss

**Comment by royka1** [comment]
I'm sorry if i was not clear, but it was solved by editing the files you mentioned and downloading the older version of assistant_helper. (I've searched for it on google and took the one with "google.assistant.embedded.v1alpha**1**.embedded_assistant_pb2" in it)

**Comment by sburrell63** [comment]
I'm not following, 
> For this you need to change the line 136 and 144 by replacing the function name from assistant_helpers.py which is in googlesamples.assistant.grpc_

replace the function name to what?


 .UPDATE Solved: Changing function calls in assistant.py lines 136 and 144 to 
assistant_helpers.log_assist_request_without_audio(c)
assistant_helpers.log_assist_response_without_audio(resp)

**Comment by maheshyadav007** [comment]
Look at the error you will understand. Function names have been updated
that is why this problem occured.Hope dis helps

**Comment by sburrell63** [comment]
Yes, this worked. I updated my original post to reflect the name changes required. Thanks!

**Comment by Zacki84** [comment]
Hi
I have the same or simular issue, and I dont know how to solve it:
Traceback (most recent call last):
  File "gassistant.py", line 33, in <module>
    assistant = Assistant()
  File "/home/pi/google-assistant-hotword-raspi/assistant.py", line 84, in __init__
    self.assistant = embedded_assistant_pb2.EmbeddedAssistantStub(self.grpc_channel)
AttributeError: 'module' object has no attribute 'EmbeddedAssistantStub'

if I take a loot in assistant.py lines 136 and 144
I have:
assistant_helpers.log_converse_request_without_audio(c)
assistant_helpers.log_converse_response_without_audio(resp)

in the previous posts you wrote to change it to:
assistant_helpers.log_assist_request_without_audio(c)
assistant_helpers.log_assist_response_without_audio(resp)
but this change nothing, still same issue.

I dont know what to do, PLEASE can you help me, thanks!
