### ISSUE TITLE
AttributeError: module 'google.assistant.embedded.v1alpha1.embedded_assistant_pb2' has no attribute 'EmbeddedAssistantStub'

### ISSUE THREAD

**Issue by TheGreyDiamond** [warchildmd/google-assistant-hotword-raspi#19]
When I run the gassistant.py file I just get 
```
Traceback (most recent call last):
  File "gassistant.py", line 33, in <module>
    assistant = Assistant()
  File "/home/pi/Hotwordy/assistant.py", line 84, in __init__
    self.assistant = embedded_assistant_pb2.EmbeddedAssistantStub(self.grpc_channel)
AttributeError: module 'google.assistant.embedded.v1alpha1.embedded_assistant_pb2' has no attribute 'EmbeddedAssistantStub'
```
Do you have any idea why this happens?

**Comment by taka78** [comment]
same here 👍

**Comment by Nerexbcd** [comment]
same here
