### ISSUE TITLE
ImportError: No module named google.assistant.embedded.v1alpha1

### ISSUE THREAD

**Issue by pi3123** [warchildmd/google-assistant-hotword-raspi#2]
Can anyone help me??

**Comment by aycgit** [comment]
you need to open it from inside a virtualenv, make sure to not install pyadio from autside virtualenv

**Comment by aycgit** [comment]
sorry nope i wrong somewhere, have you found a fix?

**Comment by aycgit** [comment]
some more info:

confirmed on pi 3b newest raspian with python 2.7 and 3

program ran using python 2.7

full error:
``
$ sudo python2.7 gassistant.py
Traceback (most recent call last):
  File "gassistant.py", line 6, in <module>
    from assistant import Assistant
  File "/home/pi/jarvis/google-assistant-hotword-raspi/assistant.py", line 6, in <module>
    from google.assistant.embedded.v1alpha1 import embedded_assistant_pb2
ImportError: No module named assistant.embedded.v1alpha1
``

problems is somewhere along the lines of python net being able to find the [embedded sdk](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha1)

**Comment by aycgit** [comment]
this should be documented but this problem can be fixed by running  sudo pip install --upgrade -r requirements.txt
   from [here](https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc)
