### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__snowboydetect)

### ISSUE THREAD

**Issue by wupanhao** [warchildmd/google-assistant-hotword-raspi#3]
(env) pi@raspberrypi:~/google-assistant-hotword-raspi $ python gassistant.py models/ok_google.pmdl

## I run on my raspberry pi 2 , but get this error
```
(env) pi@raspberrypi:~/google-assistant-hotword-raspi $ python gassistant.py models/ok_google.pmdl
Traceback (most recent call last):
  File "/home/pi/google-assistant-hotword-raspi/snowboydetect.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: dynamic module does not define init function (PyInit__snowboydetect)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gassistant.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/google-assistant-hotword-raspi/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/google-assistant-hotword-raspi/snowboydetect.py", line 21, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/google-assistant-hotword-raspi/snowboydetect.py", line 20, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dynamic module does not define init function (PyInit__snowboydetect)
```

**Comment by phdemartin** [comment]
Same problem here on Rri 3

**Comment by warchildmd** [comment]
The `snowboy.so` in this repo is for Python 2.x only.

**Comment by Ayysir** [comment]
any link to python 3 version..

**Comment by aycgit** [comment]
although this should have a version check we should first try to get it working on [2.7](https://github.com/warchildmd/google-assistant-hotword-raspi/issues/2)

**Comment by ardx160** [comment]
Same problem, any solution for this error?

**Comment by aycgit** [comment]
Ardx you need to use python2.7 but it stil wont work, im wormen on a fix today

**Comment by aycgit** [comment]
progress, it recognizes my voice but then crashes

**Comment by Andy1314Chen** [comment]
sad! I have the same problem...

**Comment by Moulde** [comment]
I don't quite understand this.
The guide in the readme clearly shows the way to create python virtual envs for both python 2.7 and 3.
And shows how to rename the _snowboydetect.so, but the the final script to run, doesn't support python 3? That's a bit odd :(

**Comment by warchildmd** [comment]
#9 added snowboy for Py3. Thanks to @Shaxine

**Comment by Shaxine** [comment]
@Moulde Since the last commit python 3 is supported. This issue was created before the python 3 support.

@warchildmd I think this issue should be marked as solved. As is causing some confusion.

**Comment by Moulde** [comment]
Ah yes suddenly it worked :) Thanks Shaxine
