### ISSUE TITLE
cannot import name assistant_helpers

### ISSUE THREAD

**Issue by gain9999** [warchildmd/google-assistant-hotword-raspi#7]
After I ran gassistant.py I got the following error. Any suggestion? 
I ran it on Pi Zero W, python 2.7.9
```
Traceback (most recent call last):
  File "gassistant.py", line 6, in <module>
    from assistant import Assistant
  File "/home/pi/google-assistant-hotword-raspi-master/assistant.py", line 9, in <module>
    from googlesamples.assistant import (
ImportError: cannot import name assistant_helpers
```

**Comment by aycgit** [comment]
did you move a file?

**Comment by aycgit** [comment]
nope i have the same problem now

**Comment by aycgit** [comment]
this issue is likely related to python not being able to find googlesamples

**Comment by aycgit** [comment]
progress: this project seems to be built for https://github.com/googlesamples/assistant-sdk-python/blob/f7f6d03a307f6bbedbbc0cbb82d88d8348c22e64/googlesamples/assistant/common_settings.py

**Comment by aycgit** [comment]
progress: https://gist.github.com/aycgit/29ad57e45b9e9d28cc9040c8fd32b1ea (needs cleanup) i currently have an alsa problem because snowboy does not close properly...

**Comment by sipvoip** [comment]
Having the same issue, I can run googlesamples-assistant-pushtotalk, but get and error when I try to use with hotword.

root@raspberry:~/google-assistant-hotword-raspi# python gassistant.py models/snowboy.umdl 
Traceback (most recent call last):
  File "gassistant.py", line 6, in <module>
    from assistant import Assistant
  File "/root/google-assistant-hotword-raspi/assistant.py", line 9, in <module>
    from googlesamples.assistant import (
ImportError: cannot import name assistant_helpers
